# Generated by Django 5.1.3 on 2024-11-24 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('risco_eminente', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('nivel_agua', models.CharField(blank=True, max_length=50, null=True)),
                ('moradores_precisam_ajuda', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em andamento', 'Em andamento'), ('Resolvido', 'Resolvido')], default='Aberto', max_length=50)),
                ('categoria', models.CharField(choices=[('Enchente', 'Enchente'), ('Deslizamento', 'Deslizamento'), ('Inundação leve', 'Inundação leve')], default='Enchente', max_length=50)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=20)),
                ('votos', models.IntegerField(default=0)),
                ('compartilhado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
