# Generated by Django 5.1.3 on 2024-11-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_enchentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='votos',
        ),
    ]
